template.yaml
Environment variable was a dummy value anyway, and won't be used until this lambda gets deployed.  Very likely we will need different values for different environments anyway.
=> Removed environment variable

cloudformation/athena.yaml
Making it a timestamp instead of a bigint makes it easier to query.
=> Changed timestamp column to be actual timestamp

cloudformation/athena.yaml, integration_tests/helpers/athenaHelper.ts
This fixes the storage location of events and the subsequent indexing and querying, so that manual testing can still work in S3.
Not included (but coming soon) are the actual CloudFormation changes to create the crawler.
=> Transactions now in new database indexed from S3

integration_tests/helpers/cloudWatchHelper.ts, integration_tests/tests/sns-lambda-tests.ts
Removed filtered events by latestlogstreams. When getting the latest log stream sometimes are there two logSteams created for single test run and some events end up in second latest logstreams. So refactored filtered events function to search in all the logStreams.
Also, removed time delay and added waitForTrue function
=> Refactor lambda tests

cloudformation/cleaning.yaml, cloudformation/filtering.yaml, cloudformation/storage.yaml
This fixes a bug where function alarms were not being triggered. It was caused by returning batch failures without enabling batch failures
(Note: [the Amazon Serverless Application Model property that I use here to enable batch item failures lacks documentation](https://github.com/aws/serverless-application-model/issues/2256))
=> BTM-184: Fix alarms

cloudformation/test-invoice-pdf-store.yaml, template-source.yaml
my first build ticket :) 
This s3 bucket to hold invoice pdfs used to test via integration tests. As these invoices files cannot be stored in github.
=> added s3 bucket to store invoice for int tests

src/handlers/store-transactions/handler.test.ts, src/handlers/store-transactions/handler.ts, src/shared/utils/date-utils.test.ts, src/shared/utils/date-utils.ts, src/shared/utils/index.ts
This fixes the bug ticket 215. Athena queries need the date format in yyyy-mm-dd and we were storing the transaction folders as yyyy-m-d which would have been a problem for the first 9 days of the month and first 9 months of the year.
=> BTM-215 Fix date and month formatting to be 2-digits to index data for athena

cloudformation/athena.yaml, cloudformation/calculation.yaml, cloudformation/config-store.yaml, cloudformation/global.yaml, cloudformation/raw-invoice-pdf-store.yaml, cloudformation/raw-invoice-textract-data-store.yaml, cloudformation/test-invoice-pdf-store.yaml, cloudformation/transaction-storage.yaml, cloudformation/validated-invoice-data-store.yaml
Use only one global log bucket for all the S3-logs, the individual logs from the buckets go into sub-folders.
This will break the deployment when merged as the old log buckets will likely not be empty at this point. I'll fix it when it happens.
=> One log bucket for all bucket logs

.github/workflows/unit-tests.yml
This fixes the unit test running and publishing so it happens when a pull request gets merged instead of when one gets opened
=> BTM-346: publish unit tests on push to main branch

cloudformation/calculation-athena.yaml, grafana-json/billing-reconciliation-dashboard.preprod.json, grafana-json/billing-reconciliation-dashboard.uat.json
Renames the last column on the dashboard table from "Message" to "Difference" as discussed in standup.
Also added more digits to the magic number values, so that they're now like 1234567.01 instead of 1234.01.
=> Small fixes to query and dashboard

src/handlers/int-test-support/handler.test.ts, src/handlers/int-test-support/handler.ts, src/handlers/int-test-support/helpers/athenaHelper.ts, src/handlers/int-test-support/helpers/cloudWatchHelper.ts, src/handlers/int-test-support/helpers/lambdaHelper.ts, src/handlers/int-test-support/helpers/mock-data/invoice/helpers.ts, src/handlers/int-test-support/helpers/s3Helper.ts, src/handlers/int-test-support/helpers/snsHelper.ts
The other day we had a weird issue where tests in the pipeline were producing different results to tests run locally. When an invoice was generated and uploaded to S3 in the pipeline it would be called undefined.json. This was happening because the signature of the `createInvoiceInS3` function had been changed to allow passing in a filename. We didn't pick up on this being a problem because `sendLambdaCommand` didn't preserve the types of the helpers it invoked. With this change it will discern the helper you're asking for the invocation of and give you a nudge if the args you've passed in don't match what it's expecting.
=> Improve int test helper types

grafana-json/billing-reconciliation-dashboard.preprod.json
- Key added for a new entry for Blue “Discrepancy is less than -1%”.
- When there is a discrepancy between the invoiced and expected amounts that is less than -1%, this is displayed in Blue
=> BTM-284 Amend colour for negative discrepancies in the dashboard

integration_tests/tests/billing-and-transaction-view-tests.ts, integration_tests/tests/s3-invoice-end-to-end-tests.ts, src/handlers/int-test-support/helpers/call-wrappers.test.ts, src/handlers/int-test-support/helpers/call-wrappers.ts
Due to a logic error that wasn't tested for, retrying was occurring even when the function call was successful.  This PR contains a fix and expanded tests.
=> BTM-473 Fix for issue where retries happened even on success

integration_tests/tests/s3-invoice-end-to-end-tests.ts, src/handlers/int-test-support/helpers/mock-data/invoice/helpers.ts
removed the assertion to check file exists in raw bucket, thought this assertion is not required as the next step checkStandardised will fail if the file is not the bucket.
Increased time out in checkStandardised function
=> BTM-430 CSV test fix

.eslintrc.yml, integration_tests/tests/s3-invoice-raw-store-tests.ts, src/handlers/int-test-support/handler.test.ts, src/handlers/int-test-support/handler.ts, src/handlers/int-test-support/helpers/athenaHelper.ts, src/handlers/int-test-support/helpers/cloudWatchHelper.ts, src/handlers/int-test-support/helpers/lambdaHelper.ts, src/handlers/int-test-support/helpers/mock-data/csv/index.ts, src/handlers/int-test-support/helpers/mock-data/invoice/helpers.ts, src/handlers/int-test-support/helpers/mock-data/invoice/invoice.ts, src/handlers/int-test-support/helpers/mock-data/invoice/types.ts, src/handlers/int-test-support/helpers/mock-data/invoice/writers.ts, src/handlers/int-test-support/helpers/s3Helper.ts
1. Added serailizableData types to allow specific types 
2. Refactored 'TestSupportEvent interface. Replaced generic 'any' type for the parameters property with defined SerializableData type
3. TestSupportEvent interface uses generic type parameter 'T extends IntTestHelpers' to capture specific value of command property
=> Btm 576 Serialisable types for runViaLambda int test helpers

integration_tests/tests/billing-and-transaction-view-tests.ts, integration_tests/tests/e2e-tests.ts, integration_tests/tests/s3-invoice-data-tests.ts, integration_tests/tests/s3-invoice-end-to-end-tests.ts, integration_tests/tests/s3-invoice-raw-store-tests.ts, integration_tests/tests/s3-invoice-standardised-line-item-tests.ts, integration_tests/tests/s3-lambda-tests.ts, integration_tests/tests/transactionCSV-to-s3-event-tests.ts, jest.e2e.config.ts, jest.integration.config.ts, src/handlers/int-test-support/config-utils/get-e2e-test-config.ts, src/handlers/int-test-support/config-utils/get-rate-config-rows.ts, src/handlers/int-test-support/config-utils/get-vendor-service-config-rows.ts, src/handlers/int-test-support/helpers/athenaHelper.ts, src/handlers/int-test-support/helpers/commonHelpers.ts, src/handlers/int-test-support/helpers/lambdaHelper.ts, src/handlers/int-test-support/helpers/mock-data/invoice/helpers.ts, src/handlers/int-test-support/helpers/mock-data/invoice/writers.ts, src/handlers/int-test-support/helpers/queryHelper.ts, src/handlers/int-test-support/helpers/testDataHelper.ts, src/handlers/int-test-support/helpers/testSetup.ts, src/handlers/int-test-support/test-constants.ts
1. Removed the afterEach from standardised-line-item-tests as it was causing query failure when running the tests in parallel and moved the deletion to globalSetup function.
2. Refactored globalSetup function and included deleting raw-invoice and raw-invoice-textract-data bucket objects.
3. Created file called test-constants to  manage the constant values throughout the tests for ease of maintenance.
4. Increased test timeout and checkStandardised poll timeout  to allow more time for the invoice to appear in standardised folder.
=> BTM-584 Fix test failures

cloudformation/dashboard-data-extraction.yaml, src/handlers/dashboard-extract/fetch-view-data.ts, src/shared/utils/athena.test.ts, src/shared/utils/athena.ts
This addresses the [last two comments](https://github.com/alphagov/di-billing-transaction-monitoring/pull/303) that were missed on the original PR.
It also increases the timeout on the lambda function to two minutes to allow time for the athena query to run.
=> BTM-533 Refactor

cloudformation/dashboard-data-extraction.yaml, src/handlers/dashboard-extract/fetch-view-data.ts, src/shared/utils/athena.ts
Using validate() to verify the view query results resulted in it doing 10 tries with a 1-second wait in between, which was not long enough to complete the view query.  So this change allows for a longer wait in this instance.
Also bumped the lambda timeout to 3 minutes, so we don't suddenly start getting timeouts in (say) six months when we have more data in the system.
=> Added longer wait when fetching view results, and longer timeout

grafana-json/README.md
Taking snapshots manually is no longer necessary, as there is a scheduled lambda function which does it automatically.
BTM-614 is the related ticket, but not worth reopening for such a minor change.
=> BTM-614: Removed unnecessary instructions on taking snapshot

cloudformation/calculation-athena.yaml, cloudformation/frontend.yaml
This PR adds the new fields to full-extract.json that will be needed for the UI for BTM-591, 589 and 650.
It also adds /`aws/vendedlogs/` to the FrontEndApiLogGroup to avoid breaking Cloudwatch Logs Constraints. Documentation [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AWS-logs-and-resource-policy.html#AWS-logs-infrastructure-CWL).
=> BTM-591 Part 1 Reconciliation table

cloudformation/calculation-athena.yaml, integration_tests/tests/dashboard-data-extraction-tests.ts, src/frontend/extract-helper.test.ts, src/frontend/extract-helper.ts, src/frontend/handlers/__snapshots__/invoice.test.ts.snap, src/frontend/views/invoice.njk
UI for the Quantity (events) table. Design can be found [here](https://app.moqups.com/DpSOLhFxFMD222IpkWjpPj8BHy6BhoyE/edit/page/a179ad680) and [this URL](https://3lcq36ez1i.execute-api.eu-west-2.amazonaws.com/invoices?contract_id=1) is for this PR stack with multi line examples under Vendor One.
Example Screenshot:
=> BTM-590 UI Quantity (events) data table

cloudformation/calculation-athena.yaml, cloudformation/invoice-athena.yaml, integration_tests/tests/dashboard-data-extraction-tests.ts, src/frontend/extract-helpers/get-invoice-banner.test.ts, src/frontend/extract-helpers/get-reconciliation-rows.test.ts, src/frontend/extract-helpers/get-reconciliation-rows.ts, src/frontend/extract-helpers/types.ts, src/frontend/handlers/__snapshots__/invoice.test.ts.snap, src/frontend/handlers/invoice.ts, src/frontend/views/invoice.njk
> One row:
> ![image](https://github.com/alphagov/di-billing-transaction-monitoring/assets/116570124/5ae35e90-85f2-4d4f-bce0-770c1b12fadf)
> One row with invoice data missing:
> ![image](https://github.com/alphagov/di-billing-transaction-monitoring/assets/116570124/c2c3159b-f083-41d8-8bd6-de9773cafd57)
> Two rows, where one has invoice data missing:
> ![image](https://github.com/alphagov/di-billing-transaction-monitoring/assets/116570124/ac7fb7be-2bc5-4dc6-b467-aa579822cda4)
> Multiple rows:
> ![image](https://github.com/alphagov/di-billing-transaction-monitoring/assets/116570124/3408ad78-07ed-402f-a2ba-887766f304a9)
=> BTM-589 UI Invoice Details Table

integration_tests/tests/s3-lambda-tests.ts, src/handlers/int-test-support/helpers/mock-data/invoice/helpers.ts, src/handlers/int-test-support/helpers/testSetup.ts
Increased Time out in waitForSubstringInLogs and checkForRawInvoice functions
empty email bucket before test execution
=> Increased Time out and empty email bucket

.eslintrc.yml, package.json, src/handlers/custom-athena-view-resource/handler.test.ts, src/handlers/custom-athena-view-resource/handler.ts, src/handlers/dashboard-extract/fetch-view-data.ts, src/handlers/int-test-support/clients.ts, src/handlers/int-test-support/helpers/mock-data/csv/objectsToCsv.test.ts, src/handlers/int-test-support/helpers/query-athena-helper.test.ts, src/handlers/int-test-support/helpers/secretsManagerHelper.ts, src/handlers/int-test-support/helpers/sesHelper.ts, src/handlers/pdf-extract/handler.ts, src/handlers/process-email/business-logic.test.ts, src/handlers/transaction-csv-to-json-event/convert/csv-to-json.test.ts, src/handlers/transaction-csv-to-json-event/convert/perform-transformations.test.ts, src/shared/constants.ts, src/shared/utils/kms/client.ts, src/shared/utils/s3.ts, src/shared/utils/sqs.ts, src/tools/delete-bucket.ts, src/tools/teardown-cf-stack.ts
CF files now use AWS::Region where possible.
A new global has also been defined for .ts files to use.
=> BTM-499: centralise references to eu-west-2

src/frontend/utils/root-dir.ts
The "fix" I added yesterday had a destructural assignment that, in retrospect, was doomed to fail. This gets rid of that and just returns dirname in higher envs
=> Root dir second fix

ui-tests/pageobjects/homepage.ts, ui-tests/pageobjects/invoicePage.ts, ui-tests/pageobjects/invoicesListPage.ts, ui-tests/pageobjects/page.ts, ui-tests/specs/breadcrumbs.spec.ts, ui-tests/specs/home.spec.ts, ui-tests/utils/extractTestDatajson.ts, ui-tests/utils/getPrettyMonthName.ts
Added below additional UI tests 
- HomepageOverview table Tests:
This tests verifies that the data displayed in the Overview table on the homepage matches with data retrieved from the latest invoices per vendor from json tests data file. 
Also, added tests to verify the correct navigation to respective contract and invoice page when contract name and vie w invoice links are clicked.
- Breadcrumbs tests
Added new suite of tests to validate the breadcrumb count to ensure that the navigation breadcrumbs are working as expected.
- moved getTable function to page file so that can be reused in homepage and invoice page tests
- Added a getLatestInvoicesByVendor to get the latest invoices per vendor to compare with UI
- Added a file getPrerttyMonth the function takes month number as input and …
=> BTM 722  overview table tests

src/frontend/extract-helpers/get-reconciliation-rows.test.ts, src/frontend/utils/percentage-discrepancy-special-case.ts
On invoice page, for reconciliation-table rows with unexpected charges, matches their status badges' style with header banner
=> BTM-710: fix unexpected-charge label

ui-tests/pageobjects/page.ts, ui-tests/specs/footer.spec.ts
In this PR, I have added UI test to ensure that clicking on Cookies link in the footer navigates to correct Cookies page by verifying the url and page title. 
-Added a. new file called footer.spec.ts and this file contains one test that checks the functionality of the cookies link in the footer. 
-Added cookies link web element and click action on page.ts file.
I haven't added test to check the content of the page as the content may not change often.
=> BTM-737 cookies page navigation test

src/frontend/extract-helpers/get-overview-rows.test.ts, src/frontend/extract-helpers/get-overview-rows.ts
Vendors which appear in config but for which we have no data to show were causing crashes when the home page tries to render the overview table.  This change causes such rows to be left off the table, which is our James-approved fix for the time being.
=> BTM-712 Now exclude empty rows from overview table

src/handlers/int-test-support/helpers/s3Helper.ts, ui-tests/testData/test.setup.ts, wdio.conf.ts
This PR addresses an issue where the currency symbol £ was being incorrectly encoded when uploading a test data file to s3. The root cause was found to be `ASCII` encoding used in putObject function.
- Modified putS3objectBasic function to accept an optional  encoding parameter. By default the encoding set to ASCII  but now it can be overridden. If UTF-8 is specified it will be used to correctly handle characters like £.
- Updated UI test data file uploading mechanism,Previously the upload was happening before each test now I changed this to onPrepare function so it is executed once.
-  Renamed `uploadExtractDataFileForUITest` function to cleanAndUploadExtractFileForUITest  and added deletion of existing file in s3 and uploading new ones.
=> BTM-713 currency fix encoding issue and optimise ui test data upload

ui-tests/specs/home.spec.ts, ui-tests/specs/invoice.spec.ts, ui-tests/utils/constants.ts, ui-tests/utils/generateExpectedOverviewTableStatus.ts, ui-tests/utils/generateExpectedStatusBannerDetails.ts
Add generateExpectedOverviewTableStatusFromPercentagePriceDifference module and utilised this function in home.spec.ts
Introduced `overviewTableStatus` in `statusLabels`
updated color codes in `percentageDiscrepencySpecialCase`
Modified the `generateExpectedBannerDetails` function to reflect new color codes
=> Btm 767 fix UI tests invoice status and color

src/frontend/handlers/__snapshots__/home.test.ts.snap, src/frontend/views/home.njk
Removed the empty columns that caused accessibility issues.
Note this causes the sole table column to widen a bit, but I don't think it looks bad:
=> BTM-718 Removed unused table columns

integration_tests/run-tests.sh, ui-tests/helpers/waits.ts, ui-tests/pageobjects/contractsPage.ts, ui-tests/pageobjects/invoicePage.ts, ui-tests/pageobjects/invoicesListPage.ts, ui-tests/pageobjects/page.ts, ui-tests/specs/invoice.spec.ts
Added new utility functin `waitForElementDisplayed` that uses webdriver `waitUntil` function. This new utility method ensures that the UI elements displayed before the test continues
Fixed UI test report path in run-tests.sh file
Added new expect statement in `beforeEach` in the invoiceSpec file to check the page title before the tests.
=> BTM 747 UI tests fixes

cloudformation/raw-invoice-textract-data-store.yaml
Tightens the permissions on Textract DLQ, which formerly had '*' for the `Principal`.
=> BTM-729 Tighten permissions on Textract DLQ

src/handlers/int-test-support/helpers/testSetup.ts
Modified the `timeout` parameter in `poll` function in `globalSetup.ts` from 60000 to 80000 to resolve recent failures in the pipeline caused by incomplete S3 object deletion.
=> Increase timeout for s3 object deletion in int tests

src/handlers/int-test-support/helpers/lambdaHelper.ts, ui-tests/testData/test.setup.ts
While running UI test after integration tests in the pipleine, the UI was using a cached version of full extract json and this causing ui test failures. So,
Added a `restartLambda` utility function that fetches the current environment variables and triggers a lambda function configuration update, effectively restarting it.
Added the restartLambda function in `cleanAndUploadExtractFileForUITest` function
=> Restart Frontend Lambda Before running UI tests

cloudformation/intTestSupport.yaml
added IAM permissions in int-support.yml to restart the frontend lambda before running ui tests to avoid cached data
=> Update IAM permission in int-support CF  for lambda restart 

cloudformation/calculation-athena.yaml
Having the event_name available in the dashboard data extract makes computing shortfall events a lot easier.  The dashboard extract ultimately is just a query to `btm_billing_and_transactions_curated`, so we just need to carry along the event name through a few of the upstream views.
This change can go through on its own ahead of time since nothing else will be accessing that field.
=> BTM-773 carry event name into extract

src/handlers/custom-athena-view-resource/handler.test.ts, src/handlers/custom-athena-view-resource/handler.ts, src/shared/utils/athenaV3.ts, src/shared/utils/custom-resource-utils.ts, src/tools/teardown-cf-stack.ts
After going down multiple rabbit holes with this, the simplest solution is just to ignore the Athena Views on deletion of a stack as they will just be deleted as part of the database anyway...
=> Btm 832 fix teardown

src/tools/batch-day.sh, src/tools/batch-month.sh
added commands to rerun the previous aws command again making it easier to see if there were any errors in the first batch as there are ~80,000 log lines per command
=> add retry into batch bucketing scripts

src/handlers/event-bucketing/business-logic.ts, src/shared/utils/s3/base.ts
there are too many generic info logs spammed during bucketing to tell what the problem is in production. Bucketing retested in dev and still working so added extra logging also to help debug prod issue.
=> change logging for S3 access to debug and add info logs for bucketing

src/handlers/filter/business-logic.test.ts, src/handlers/filter/business-logic.ts, src/handlers/filter/types.ts
ID Events relating to Driving Licenses will be supported. For now, we want to only consider these events if the License was issued by DVLA.
=> BTM-685 Filter non DVLA if Driving license is set

src/handlers/filter/business-logic.test.ts, src/handlers/filter/business-logic.ts, src/handlers/filter/types.ts
This modifies the format of the 'issuedBy' that we are expecting from the TxMA self serve. The supplied config was resulting in an output that has the final string in an array unexpectedly.
=> BTM-918 Fix for Filter non DVLA if Driving license is set
