- .gitignore
- README.md
- src/handlers/filter.js
- template.yaml
Simple SNS topic to mimic the real SNS topic we use once we get to production
> BTM-40: Adding SNS topic

- template.yaml
Adding permissions to SNS queue to send message to SQS
> BTM-73: Adding SNS permissions

- template.yaml
More attempts to get permissions on KMS working - trying to be broad to start with then narrow it down later.
> Btm 73 permissions

- template.yaml
> BTM-73: More permissions updates

- .gitignore
- jest.config.js
- src/handlers/filter/handler.test.ts
- src/handlers/filter/handler.ts
- src/handlers/storage.js
- src/handlers/store/handler.test.ts
- src/handlers/store/handler.ts
- template.yaml
- test-helpers/SQS.ts
- webpack.config.js
BTM-63: Adding the lambda to store the records in the DB
* Touched up the filter tests to improve coverage
* Added coverage to the test output
> Btm 63 create store lambda

- README.md
- integration_tests/clients/cloudWatchLogsClient.ts
- integration_tests/clients/dynamoDbClient.ts
- integration_tests/clients/snsClient.ts
- integration_tests/helpers/cloudWatchHelper.ts
- integration_tests/helpers/dynamoDBHelper.ts
- integration_tests/helpers/snsHelper.ts
- integration_tests/tests.ts
- jest.integration.config.ts
- package-lock.json
- package.json
Refactored tests to use aws sdk javascript v3 and added clients, helper classes
added jest test integration config file
updated readme to run the integration tests
> Btm 84 filter lambda tests

- README.md
- integration_tests/helpers/cloudWatchHelper.ts
- integration_tests/helpers/dynamoDBHelper.ts
- integration_tests/helpers/snsHelper.ts
- integration_tests/setup/testEnvVar.ts
- integration_tests/tests.ts
moved env variables to separate files
added test for clean and store functions
removed filter patten parameter in getFilteredLogEvents to use the method for different lambda functions
test condition now checks from the filtered events there should not be any error
> Btm 62 clean lambda tests

- src/handlers/clean/handler.test.ts
One small bit of code coverage was missing; this new test should complete it.
> Added test that completes the last bit of testing code coverage

- integration_tests/helpers/cloudWatchHelper.ts
- integration_tests/helpers/commonHelpers.ts
- integration_tests/helpers/snsHelper.ts
- integration_tests/payloads/snsEventPayload.ts
- integration_tests/payloads/snsEventPayloads.ts
- integration_tests/tests.ts
added negative scenarios
separated SNS payload to separate file
> Btm 127 negative tests

- cloudformation/storage.yaml
Adding versioning to access control log bucket as per GDS rules
> BTM-105: Fixing checkov failures in deployment

- integration_tests/payloads/snsEventPayload.ts
- integration_tests/tests/sns-lambda-tests.ts
- integration_tests/tests/sns-s3-tests.ts
formatted test files
refactored describe and test statements to understand the expect results better
> refactored describe and test statements

- cloudformation/athena.yaml
- cloudformation/cleaning.yaml
- template-source.yaml
Adding Athena and Glue and the s3 buckets to support them
> Btm 134 athena

- cloudformation/athena.yaml
- src/handlers/store/handler.ts
Partition based on year first, not event type.
> Trying out partitioning data like txma does it 

- integration_tests/clients/athenaClient.ts
- integration_tests/helpers/athenaHelper.ts
- integration_tests/helpers/s3Helper.ts
- integration_tests/tests/athena-query-tests.ts
- package-lock.json
- package.json
> Btm 136 athena tests

- integration_tests/helpers/s3Helper.ts
- integration_tests/tests/athena-query-tests.ts
- integration_tests/tests/s3-vat-tests.ts
- integration_tests/tests/sns-s3-tests.ts
- package.json
refactored getS3ItemList function to pass bucketNameMatchString as parameter
added s3 vat tests
updated local test config to ignore athena and s3 vat tests
> Btm 117 s3 vat test

- .gitignore
- README.md
- jest.integration.config.ts
- package-lock.json
- package.json
added configuration for allure report
updated readme to generate allure report
> Btm 109 allure report

- integration_tests/tests/s3-invoice-data-tests.ts
added simple tests to check invoice created bucket exists in s3
> added s3 bucket exists tests

- integration_tests/helpers/cloudWatchHelper.ts
- integration_tests/tests/s3-rawinvoice-extract-function-tests.ts
- integration_tests/tests/sns-lambda-tests.ts
- integration_tests/tests/sns-s3-tests.ts
Passed testStartTime as parameter to cloudwatch helper checkGivenStringLogExists function
> Fix cloudwatch filtered log func

- integration_tests/helpers/s3Helper.ts
- integration_tests/tests/athena-query-tests.ts
- integration_tests/tests/s3-invoice-data-tests.ts
- integration_tests/tests/sns-s3-tests.ts
added bucket prefix to getS3ItemsList so it will. retrieve items with the folder btm_transactions
> added bucketPrefix to getS3ItemsList

- integration_tests/tests/s3-standardised-lambda-tests.ts
added standardised function test to check no errors in standardised function cloudwatch logs.
This test will be improved once the we implement standardised- invoice-storage- function with validations
> btm-277 function test

- integration_tests/tests/athena-query-tests.ts
- integration_tests/tests/s3-vat-tests.ts
1.fixed database name
2.removed whitespaces from s3 vat config response
> fixed failing int tests

- integration_tests/helpers/s3Helper.ts
- integration_tests/tests/s3-invoice-data-tests.ts
- integration_tests/tests/s3-invoice-raw-store-tests.ts
1. Fixed bucket name for one of the test
2. one of the integration test requires manually upload the invoice to the test-invoice-pdf bucket so added a condition to check the file exists in the bucket.
> Fix bucket name int test

- README.md
- cloudformation/calculation-athena.yaml
- cloudformation/filtering.yaml
- cloudformation/global.yaml
- package.json
- template-source.yaml
This looks far more straight forward than it was to find this solution. Somewhere on the way were about 10 nested cloudformation functions to extract and combine the correct parts of the stacks, but luckily I could resolve that...
TIL: If you have to use a complicated string interpolation in multiple places, put it in an SSM-Parameter and reference that instead (since there are no variables in CF...).
> BTM-320: Fix for failures in dev environment

- integration_tests/helpers/commonHelpers.ts
- integration_tests/tests/transaction-view-athena-tests.ts
added additional test for event generated  last year to check the effective from price
> Btm 241 additional test

- cloudformation/cleaning.yaml
- cloudformation/extraction.yaml
- cloudformation/raw-invoice-textract-data-store.yaml
- cloudformation/standardised-invoice-storage.yaml
Make the dead letter queues (x3) and lambdas (x3) of the billing flow produce CloudWatch (CW) alarms.
> BTM-185 Add CloudWatch Alarms for Billing(Invoicing) DLQs and Functions

- .github/workflows/deploy-pr-stack-and-run-int-tests.yml
- .github/workflows/deploy-to-dev-and-build.yml
- .github/workflows/tear-down-pr-stack-on-closing-pr.yml
- .github/workflows/unit-tests.yml
- package.json
This is for testing the functionality, but feel free to review, it's not much.
> BTM-383: Run int-tests on PR

- integration_tests/tests/s3-invoice-raw-store-tests.ts
increased the timeout in poll function
> increased time out

- integration_tests/tests/s3-invoice-raw-store-tests.ts
- src/handlers/int-test-support/helpers/commonHelpers.ts
- src/handlers/int-test-support/helpers/mock-data/invoice/helpers.ts
- src/handlers/int-test-support/helpers/mock-data/invoice/writers.ts
added more console logs to debug the failing test in pipeline. The raw invoice pdf file is uploaded as undefined filename in s3.
The particular test is passing locally when running against DEV locally whereas failing in pipeline. These logs will be removed once the test is fixed.
> More logs to investigate failing tests

- integration_tests/tests/s3-invoice-raw-store-tests.ts
- integration_tests/tests/s3-standardised-lambda-tests.ts
- src/handlers/int-test-support/helpers/commonHelpers.ts
- src/handlers/int-test-support/helpers/mock-data/invoice/helpers.ts
- src/handlers/int-test-support/helpers/mock-data/invoice/writers.ts
skipped failing tests to promote the latest config changes to staging environment, the functionality is working as expected only there is issue in the integration test.
This unblock the testing in staging environment. The changes will reverted back once the code is promoted to staging environment.
> skip failing tests

- integration_tests/tests/s3-invoice-raw-store-tests.ts
- integration_tests/tests/s3-standardised-lambda-tests.ts
- src/handlers/int-test-support/helpers/mock-data/invoice/helpers.ts
Removed skip from the tests
passed filename as one of the parameter to createInvoiceInS3 function
> FIX: added filename to createInvoiceInS3

- cloudformation/calculation-athena.yaml
- cloudformation/extraction.yaml
- cloudformation/raw-invoice-textract-data-store.yaml
- cloudformation/standardised-invoice-storage.yaml
- package.json
- sonar-project.properties
- src/handlers/int-test-support/helpers/lambdaHelper.ts
and a few other things like superfluous quotes,  and limiting the unit tests to 4 workers.
> BTM-412: Fix sonar scan issues

- cloudformation/calculation-athena.yaml
- integration_tests/tests/billing-and-transaction-view-tests.ts
Added effective_to to rates table to simplify transactions query.
> BTM-338 query refactor

- integration_tests/tests/billing-and-transaction-view-tests.ts
removed read vendorname from configstack due to access error in pipeline instead used driven the vendorname from  prettyVendorNameMap when creating the invoice
> Fix:Failing Billing trans view tests in pipeline

- cloudformation/intTestSupport.yaml
updated condition for sns resource in int test support yaml
> Btm 459 update int test support

- src/handlers/int-test-support/helpers/testSetup.ts
added poll condition to check the bucket is empty after the deleteS3 command
> added poll condition to check bucket empty

- integration_tests/tests/e2e-tests.ts
Timeout for poll condition was very high so reduced to 120000
> fixed timeout value

- cloudformation/calculation-athena.yaml
- cloudformation/invoice-athena.yaml
Sets a flag that will hopefully enable partitioning.
> BTM-486 enable partitioning

- jest.e2e.config.ts
- jest.integration.config.ts
- src/handlers/int-test-support/helpers/mock-data/invoice/helpers.ts
1. Increased check standardised function timeout further more 
2. Increased jest test timeout in config files
3. removedContents!==undefined filtering in listS3objects in checkStandardised as Contents is expected be an array
> increased timeout in checkstandardised fn poll and jest test Timeout

- src/tools/teardown-cf-stack.ts
created separate function for listingStack resources
replaced DescribeStackResourcesCommand with ListStackResourcesCommand for pagination as in the AWS docs it suggested to ListStackResourcesCommand instead of DescribeStackResourcesCommand for pagination https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/describe-stack-resources.html
update type StackResource to StackResourceSummary as StackRescource not exists in ListStackResourcesCommand
Added condition to do tryToDelete
> Btm 585 tear down script fix

- .github/workflows/build-and-push-testing-image.yaml
Reverts alphagov/di-billing-transaction-monitoring#329
> Revert "FIX Update GH Action for Build and Push Testing Image"

- integration_tests/Dockerfile
- integration_tests/Dockerfile-e2e
update ensurepip module to the latest version. This might not directly fix the current problem but improves the installation process by ensuring we have the latest version of the module.
> Upgrade ensurepip module to latest version 

- integration_tests/tests/email-storage-tests.ts
-added skip to the email storage tests as the test is failing in dev and build when running via int test support function
> added skip to email storage tests

- src/frontend/extract-helper.test.ts
- src/frontend/extract-helper.ts
- src/frontend/handlers/__snapshots__/invoice.test.ts.snap
- src/frontend/views/invoice.njk
UI for the Price table. Design can be found [here](https://app.moqups.com/DpSOLhFxFMD222IpkWjpPj8BHy6BhoyE/edit/page/a179ad680) and [this URL](https://c2sq4v6x75.execute-api.eu-west-2.amazonaws.com) is for this PR stack with multi line examples under Vendor One.
> BTM-665 Data and UI for the Price Table

- src/frontend/views/index.njk
UI for the homepage navigation panel as designed in the [moqup here](https://app.moqups.com/DpSOLhFxFMD222IpkWjpPj8BHy6BhoyE/edit/page/ac4619028).
James has 👍🏼 already.
> BTM-663 UI homepage navigation panel

- src/frontend/handlers/__snapshots__/contracts.test.ts.snap
- src/frontend/handlers/__snapshots__/invoice.test.ts.snap
- src/frontend/handlers/__snapshots__/invoices.test.ts.snap
- src/frontend/handlers/invoice.test.ts
- src/frontend/views/common/layout/base.njk
- src/frontend/views/invoice.njk
- src/frontend/views/status-guidance.njk
This PR is for the `Status Guidance` section in the mock up [here] (https://app.moqups.com/DpSOLhFxFMD222IpkWjpPj8BHy6BhoyE/edit/page/a179ad680) and can be viewed on the temporary PR URL [here](https://2t3zeakm71.execute-api.eu-west-2.amazonaws.com).
> BTM-664 UI Status Guidance

- integration_tests/tests/email-storage-tests.ts
- src/handlers/int-test-support/helpers/sesHelper.ts
Simplified email params type which aims to narrow down and debug the issue with attachments not working correctly when using Test_int_support_function
> Simplified emailParams type

- src/frontend/handlers/__snapshots__/invoice.test.ts.snap
- src/frontend/views/invoice.njk
Nothing too exciting, just a simple component swap.
> BTM-750 Made status guidance use details instead of accordion

- package.json
I failed to add the event batching npm command with the previous event batching PR.
> Event batching npm command

- src/frontend/handlers/__snapshots__/invoice.test.ts.snap
- src/frontend/views/status-guidance.njk
Task from ticket to update status guidance was skipped on earlier PR.
> BTM-726 Updated status guidance

- package-lock.json
- package.json
- src/frontend/handlers/__snapshots__/invoice.test.ts.snap
- src/frontend/views/invoice.njk
- ui-tests/specs/invoice.spec.ts
Updated chrome driver version
Fixed Measured and invoice table Line Item header to Line item to be consistent with other tables
> Fixed Line item instead of Line Item and updated chrome driver version

- src/handlers/int-test-support/handler.ts
- src/handlers/int-test-support/helpers/lambdaHelper.ts
- src/handlers/int-test-support/types.ts
- ui-tests/utils/getPrettyMonthName.ts
Added restartLambda function to the `HelperDict interface and functionMap` 
Changed the locale in the `prettyMonthName` function changed from `default` to en-US` to standardise month name formatting
> BTM-803-Fix-pipeline-errors

- cloudformation/cleaning.yaml
- cloudformation/csv-extraction.yaml
- cloudformation/custom-athena-view-resource.yaml
- cloudformation/email-processing.yaml
- cloudformation/filtering.yaml
- cloudformation/pdf-extraction.yaml
- cloudformation/pdf-standardisation.yaml
- cloudformation/raw-invoice-textract-data-store.yaml
- cloudformation/standardised-invoice-storage.yaml
- cloudformation/transaction-storage.yaml
Not sure why all those reformats happened, but only the retention time changes should make a difference.
> CHORE: Maximum retention time (14 days) on DLQs

- template-source.yaml
removing these resources has deployed as far as build 🤞 we can revivify them
> re-enable frontend

- template-source.yaml
> disable-frontend-dev-build

- cloudformation/frontend.yaml
- template-source.yaml
Merging this will kick of the code's long march to production. Make sure that's what you want to do before merging.
> Remove the chocks

- CODEOWNERS
just a Clean task to remove leavers for code owner
> removed leavers from code owner

- .github/workflows/deploy-ephdev-stack-and-run-tests.yml
- README.md
Fixed the ephdev workflow and updated README.md file.
> Fix ephdev workflow and update README.md with instructions

- src/frontend/README.md
- src/frontend/handlers/__snapshots__/accessibility.test.ts.snap
- src/frontend/handlers/__snapshots__/contracts.test.ts.snap
- src/frontend/handlers/__snapshots__/cookies.test.ts.snap
- src/frontend/handlers/__snapshots__/home.test.ts.snap
- src/frontend/handlers/__snapshots__/invoice.test.ts.snap
- src/frontend/handlers/__snapshots__/invoices.test.ts.snap
- src/frontend/handlers/accessibility.test.ts
- src/frontend/handlers/accessibility.ts
- src/frontend/pages.test.ts
- src/frontend/pages.ts
- src/frontend/views/accessibility.njk
- src/frontend/views/common/layout/base.njk
Sigend-off-by: VladGavrilet <vlad-andrei.gavrilet@digital.cabinet-office.gov.uk>
Adding Components for Accessibility page
> Added Accesability page components

- package-lock.json
- package.json
Move chromedriver to 118 to get ui tests working again
> Bump chrome webdriver to 118

- package-lock.json
- package.json
Additional package updates for security ITHC
> BTM-866 Update Semver and associated packages

- cloudformation/intTestSupport.yaml
- package-lock.json
- package.json
fixing UI testing by bumping Chrome driver version
> fix UI testing by bumping Chrome driver version
